- hosts: localhost

  tasks:
  
    - name: Setting up Security/Firewall Group
      ec2_group:
         name: new_ec2
         description: Rules Allowing Traffic on port 22 and 80
         region: us-east-2
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
         rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Provision a EC2 Instance
      ec2:
         key_name: ec2
         region: us-east-2
         instance_type: t2.micro
         image: ami-077e31c4939f6a2f3
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
           Name: devserver
           Owner: Saren
         monitoring: no
         vpc_subnet_id: subnet-23cb3a5e
         assign_public_ip: yes
         group: new_ec2
      register: ec2_out

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out.instances}}'
      
    - name: Store public ip of new host
      add_host:
         hostname: "{{ item.public_ip }}"
         groupname: launched
      with_items: "{{ ec2_out.instances }}"
      
- name: Host a webserver
  become: true
  hosts: launched
  tasks:
    - package:
         name: httpd
         state: present
    - service:
         name: httpd
         state: started
    - copy:
         src: index.html
         dest: /var/www/html
    - copy:
         src: west.jpg
         dest: /var/www/html
